export default {
    haircolors: [
        'Braun',
        'Hellbraun',
        'Dunkelbraun',
        'Blond',
        'Hellblond',
        'Dunkelblond',
        'Weißblond',
        'Grau',
        'Rot',
        'Schwarz'
    ],
    eyecolors: [
        'Braun',
        'Hellbraun',
        'Dunkelbraun',
        'Grau',
        'Rot',
        'Grün',
        'Hellgrün',
        'Dunkelgrün',
        'Smaragdgrün',
        'Blau',
        'Hellblau',
        'Himmelblau',
        'Eisblau',
        'Meerblau',
        'Türkis',
        'Violett',
        'Schwarz'
    ],
    nations: [
        {
            name: 'Tasperin',
            url: 'https://wiki.athalon.net/index.php/Kaiserliche_Monarchie_Tasperin',
            cities: [
                'Carviel',
                'Schwarzwasser',
                'Linnigh',
                'Auenthal',
                'Wolfshalm',
                'Faywell',
            ],
        },
        {
            name: 'Sorridia',
            url: 'https://wiki.athalon.net/index.php/K%C3%B6nigreich_Sorridia',
            cities: [
                'Montebrillo',
                'Fortifa',
                'Jevasqèz',
                'Matoléz',
            ],
        },
        {
            name: 'AlBastra',
            url: 'https://wiki.athalon.net/index.php/Kalifat_Al%27bastra',
            cities: [
                'Mina Farah',
                "Waha'kandh",
                'Schattpur',
                'Kualtan',
            ],
        },
        {
            name: 'Silventrum',
            url: 'https://wiki.athalon.net/index.php/Vereinigte_Provinzen_von_Silventrum',
            cities: [
                'Zweibach',
                'Windwarden',
                'Steunvik',
                'Bischoffelden',
            ],
        },
        {
            name: 'Großalbion',
            url: '',
            cities: [
                'Asmaeth',
                'Molder',
                'Rodstedt',
                'Nordingen',
                'Sechseich',
                'Oberrath',
                'Sodenmark',
                'Lürch',
                'Dornbach',
                'Grünfels',
                'Ringen',
                'Braundorf',
                'Hagenstein',
                'Brist',
                'Kirkmore',
                'Averssire',
                'Ochsenbach',
                'Mouray',
                'Gaelaught',
                'Leyghean',
                'Deas Mumhain',
                'Chill Dara',
                'Sligaec',
                'Tyr Eoghain',
                'Ulaydh',
            ],
        },
        {
            name: 'Haldar',
            url: 'https://wiki.athalon.net/index.php/Haldarische_Stammesl%C3%A4nder',
            cities: [
                'Nebelhafen',
                'Siefhof',
                'Talgrund',
                'Haflof',
            ],
        },
        {
            name: 'Patrien',
            url: 'https://wiki.athalon.net/index.php/K%C3%B6nigreich_Patrien',
            cities: [
                'Olapaso',
                'Corastella',
                'Vadez',
                'Figurréz',
            ],
        },
        {
            name: 'Fallice',
            url: 'https://wiki.athalon.net/index.php/K%C3%B6nigreich_Fallice',
            cities: [
                'Hilton',
                'Tremban',
                'Graméntis',
                'Pas - Baltan',
            ],
        },
        {
            name: 'Kurmark',
            url: 'https://wiki.athalon.net/index.php/Erzbistum_Kurmark',
            cities: [
                'Zandig',
                'Sôlfurt',
                'Zinten',
                'Berent',
                'Königsberg',
                'Lötzen',
            ]
        }
    ]
}
