export default {
    haircolors: [
        'Braun',
        'Hellbraun',
        'Dunkelbraun',
        'Blond',
        'Hellblond',
        'Dunkelblond',
        'Weißblond',
        'Grau',
        'Rot',
        'Schwarz'
    ],
    eyecolors: [
        'Braun',
        'Hellbraun',
        'Dunkelbraun',
        'Grau',
        'Rot',
        'Grün',
        'Hellgrün',
        'Dunkelgrün',
        'Smaragdgrün',
        'Blau',
        'Hellblau',
        'Himmelblau',
        'Eisblau',
        'Meerblau',
        'Türkis',
        'Violett',
        'Schwarz'
    ],
    cities: {
        Tasperin: [
            'Carviel',
            'Schwarzwasser',
            'Linnigh',
            'Auenthal',
            'Wolfshalm',
            'Faywell',
        ],
        Sorridia: [
            'Montebrillo',
            'Fortifa',
            'Jevasqèz',
            'Matoléz',
        ],
        AlBastra: [
            'Mina Farah',
            "Waha'kandh",
            'Schattpur',
            'Kualtan',
        ],
        Silventrum: [
            'Zweibach',
            'Windwarden',
            'Steunvik',
            'Bischoffelden',
        ],
        Großalbion: [
            'Asmaeth',
            'Molder',
            'Rodstedt',
            'Nordingen',
            'Sechseich',
            'Oberrath',
            'Sodenmark',
            'Lürch',
            'Dornbach',
            'Grünfels',
            'Ringen',
            'Braundorf',
            'Hagenstein',
            'Brist',
            'Kirkmore',
            'Averssire',
            'Ochsenbach',
            'Mouray',
            'Gaelaught',
            'Leyghean',
            'Deas Mumhain',
            'Chill Dara',
            'Sligaec',
            'Tyr Eoghain',
            'Ulaydh',
        ],
        Haldar: [
            'Nebelhafen',
            'Siefhof',
            'Talgrund',
            'Haflof',
        ],
        Patrien: [
            'Olapaso',
            'Corastella',
            'Vadez',
            'Figurréz',
        ],
        Fallice: [
            'Hilton',
            'Tremban',
            'Graméntis',
            'Pas - Baltan',
        ],
        Kurmark: [
            'Zandig',
            'Sôlfurt',
            'Zinten',
            'Berent',
            'Königsberg',
            'Lötzen',
        ],
    },
}
